# Generated by Django 5.2.5 on 2025-10-28 14:45

import apps.correo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('empresas', '0002_empresa_email_host_empresa_email_last_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_uid', models.CharField(help_text='UID único del mensaje en el servidor de correo', max_length=255)),
                ('asunto', models.CharField(max_length=512)),
                ('remitente', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('empresa', 'msg_uid')},
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.correo.models.email_attachment_path)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('documento_procesado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjunto_origen', to='documentos.documento')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correo.correo')),
            ],
        ),
    ]
