# Generated by Django 5.2.5 on 2025-09-04 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_dropboxcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxcredential',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dropboxcredential',
            name='connected_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='googledrivecredential',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='googledrivecredential',
            name='connected_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
