# Generated by Django 5.2.5 on 2025-09-08 14:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integraciones", "0003_dropboxcredential_account_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dropboxcredential",
            name="account_email",
        ),
        migrations.RemoveField(
            model_name="dropboxcredential",
            name="connected_at",
        ),
        migrations.RemoveField(
            model_name="googledrivecredential",
            name="account_email",
        ),
        migrations.RemoveField(
            model_name="googledrivecredential",
            name="connected_at",
        ),
    ]
