# Generated by Django 5.2.5 on 2025-10-27 21:22

import apps.empresas.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PN_HONORARIOS', 'Persona natural - honorarios'), ('PN_GIRO', 'Persona natural con giro (1ª cat.)'), ('PJ', 'Persona jurídica (PyME)')], max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255)),
                ('actividad_economica', models.CharField(blank=True, max_length=10)),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=255)),
                ('domicilio_numero', models.CharField(blank=True, max_length=20)),
                ('domicilio_comuna', models.CharField(blank=True, max_length=100)),
                ('domicilio_region', models.CharField(blank=True, max_length=100)),
                ('sistema_facturacion', models.CharField(blank=True, choices=[('SII_GRATIS', 'SII_GRATIS'), ('MERCADO', 'MERCADO')], max_length=20)),
                ('certificado_usa', models.BooleanField(default=False)),
                ('tipos_dte_autorizados', models.JSONField(blank=True, default=list)),
                ('habilitado_dte', models.BooleanField(default=False)),
                ('solo_honorarios', models.BooleanField(default=False)),
                ('tasa_retencion_honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rep_rut', models.CharField(blank=True, max_length=12)),
                ('rep_nombre', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT con guión (ej: 76262345-K)', max_length=12, unique=True)),
                ('razon_social', models.CharField(help_text='Nombre o razón social inscrita en SII', max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('codigo_actividad', models.CharField(blank=True, max_length=6)),
                ('tipo_societario', models.CharField(choices=[('PN', 'Persona Natural con Giro'), ('EIRL', 'E.I.R.L.'), ('SPA', 'SpA'), ('LTDA', 'Limitada'), ('SA', 'S.A.'), ('OTRO', 'Otro')], default='SPA', max_length=10)),
                ('regimen_tributario', models.CharField(choices=[('14D8', 'Pro PyME Transparente (14 D 8)'), ('14D3', 'Pro PyME General (14 D 3)'), ('GEN', 'Régimen General'), ('PCAT', 'Régimen Primera Categoría'), ('SCAT', 'Régimen Segunda Categoría')], default='14D3', max_length=4)),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('ingresos_12m_uf', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos por ventas últimos 12 meses (en UF)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.empresas.models.empresa_logo_upload_to)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contribuyente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='empresas.contribuyente')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('analista', 'Analista')], default='admin', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de Empresa',
                'verbose_name_plural': 'Membresías de Empresa',
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['rut'], name='empresas_em_rut_03476c_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['razon_social'], name='empresas_em_razon_s_1fdde1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresausuario',
            unique_together={('usuario', 'empresa')},
        ),
    ]
