# Generated by Django 5.2.5 on 2025-08-25 23:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('analista', 'Analista')], default='admin', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membresía de Empresa',
                'verbose_name_plural': 'Membresías de Empresa',
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contacto_email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contacto_telefono',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='regimen',
        ),
        migrations.AddField(
            model_name='empresa',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_actividad',
            field=models.CharField(blank=True, help_text='Código actividad económica SII (opcional)', max_length=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_actividades',
            field=models.DateField(blank=True, help_text='Fecha de inicio de actividades ante el SII', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ingresos_12m_uf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos por ventas últimos 12 meses (en UF). Sirve para clasificar Micro/Pequeña/Mediana.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_tributario',
            field=models.CharField(choices=[('14D8', 'Régimen Pro PyME Transparente (14 D 8)'), ('14D3', 'Régimen Pro PyME General (14 D 3)'), ('GEN', 'Régimen General')], default='14D3', max_length=4),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ej: +56 9 8765 4321', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_societario',
            field=models.CharField(choices=[('PN', 'Persona Natural con Giro'), ('EIRL', 'E.I.R.L.'), ('SPA', 'SpA'), ('LTDA', 'Limitada'), ('SA', 'S.A.'), ('OTRO', 'Otro')], default='SPA', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='comuna',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, help_text='Giro o actividad económica principal', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(help_text='Nombre o razón social inscrita en SII', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(help_text='RUT con guión (ej: 76262345-K)', max_length=12, unique=True),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['rut'], name='empresas_em_rut_03476c_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['razon_social'], name='empresas_em_razon_s_1fdde1_idx'),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='empresausuario',
            unique_together={('usuario', 'empresa')},
        ),
    ]
