# Generated by Django 5.2.5 on 2025-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(blank=True, help_text='Ej: imap.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_password',
            field=models.CharField(blank=True, help_text='Se recomienda usar una contraseña de aplicación', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, default=993, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
