# Generated by Django 5.2.5 on 2025-08-26 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresausuario_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_actividad',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_inicio_actividades',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ingresos_12m_uf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos por ventas últimos 12 meses (en UF)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='regimen_tributario',
            field=models.CharField(choices=[('14D8', 'Pro PyME Transparente (14 D 8)'), ('14D3', 'Pro PyME General (14 D 3)'), ('GEN', 'Régimen General')], default='14D3', max_length=4),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
