# Generated by Django 5.2.5 on 2025-09-16 15:44

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_codigo_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.empresas.models.empresa_logo_upload_to),
        ),
    ]
