# Generated by Django 5.2.5 on 2025-10-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PN_HONORARIOS', 'Persona natural - honorarios'), ('PN_GIRO', 'Persona natural con giro (1ª cat.)'), ('PJ', 'Persona jurídica (PyME)')], max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255)),
                ('actividad_economica', models.CharField(blank=True, max_length=10)),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=255)),
                ('domicilio_numero', models.CharField(blank=True, max_length=20)),
                ('domicilio_comuna', models.CharField(blank=True, max_length=100)),
                ('domicilio_region', models.CharField(blank=True, max_length=100)),
                ('sistema_facturacion', models.CharField(blank=True, choices=[('SII_GRATIS', 'SII_GRATIS'), ('MERCADO', 'MERCADO')], max_length=20)),
                ('certificado_usa', models.BooleanField(default=False)),
                ('tipos_dte_autorizados', models.JSONField(blank=True, default=list)),
                ('habilitado_dte', models.BooleanField(default=False)),
                ('solo_honorarios', models.BooleanField(default=False)),
                ('tasa_retencion_honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rep_rut', models.CharField(blank=True, max_length=12)),
                ('rep_nombre', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='contribuyente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='empresas.contribuyente'),
        ),
    ]
