# Generated by Django 5.2.5 on 2025-08-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedorcontacto',
            options={'ordering': ['nombre'], 'verbose_name': 'Contacto de proveedor', 'verbose_name_plural': 'Contactos de proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_empresa_b754b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_empresa_283ac7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='proveedores.categoriaproveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(help_text='Ej: 12345678-5', max_length=12, unique=True),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['rut'], name='proveedores_rut_f2c731_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['razon_social'], name='proveedores_razon_s_7bec47_idx'),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='empresa',
        ),
    ]
