# Generated by Django 5.2.5 on 2025-08-22 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_rut_f2c731_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_razon_s_7bec47_idx',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(help_text='Ej: 12345678-5', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('owner', 'rut')},
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['owner', 'rut'], name='proveedores_owner_i_6d7d72_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['owner', 'razon_social'], name='proveedores_owner_i_ad8b09_idx'),
        ),
    ]
