# Generated by Django 5.2.5 on 2025-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_share_data_usuario_two_fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='two_fa_recovery_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
