# Generated by Django 5.2.5 on 2025-09-15 18:13

import apps.usuarios.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.usuarios.models.avatar_upload_to)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('time_zone', models.CharField(default='America/Santiago', max_length=64)),
                ('idioma_pref', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5)),
                ('empresa_nombre', models.CharField(blank=True, max_length=160, verbose_name='Razón social')),
                ('empresa_fantasia', models.CharField(blank=True, max_length=160, verbose_name='Nombre de fantasía')),
                ('empresa_rut', models.CharField(blank=True, max_length=20, verbose_name='RUT')),
                ('empresa_giro', models.CharField(blank=True, max_length=160, verbose_name='Giro')),
                ('empresa_telefono', models.CharField(blank=True, max_length=30)),
                ('empresa_email', models.EmailField(blank=True, max_length=254)),
                ('empresa_web', models.URLField(blank=True)),
                ('empresa_region', models.CharField(blank=True, max_length=100)),
                ('empresa_comuna', models.CharField(blank=True, max_length=100)),
                ('empresa_direccion', models.CharField(blank=True, max_length=220)),
                ('empresa_logo', models.ImageField(blank=True, null=True, upload_to=apps.usuarios.models.company_logo_upload_to)),
                ('color_primario', models.CharField(blank=True, help_text='#E2261C', max_length=7)),
                ('color_secundario', models.CharField(blank=True, help_text='#232323', max_length=7)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_whatsapp', models.BooleanField(default=False)),
                ('recibe_boletin', models.BooleanField(default=False)),
                ('sii_regimen', models.CharField(blank=True, help_text='Ej: ProPyme, 14D3, 14A, etc.', max_length=80)),
                ('sii_actividad', models.CharField(blank=True, max_length=160)),
                ('sii_cod_sii', models.CharField(blank=True, max_length=12, verbose_name='Cód. actividad SII')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
