# Generated by Django 5.2.5 on 2025-09-16 15:44

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.usuarios.models.user_avatar_upload_to),
        ),
    ]
