# Generated by Django 5.2.5 on 2025-08-17 23:53

import apps.documentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.documentos.models.doc_upload_to)),
                ('hash_sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('tipo', models.CharField(blank=True, choices=[('factura_afecta', 'Factura afecta'), ('factura_exenta', 'Factura exenta'), ('boleta', 'Boleta'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_sii', models.CharField(blank=True, max_length=50)),
                ('ocr_json', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['empresa', 'rut_proveedor', 'folio'], name='documentos__empresa_8f85d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'hash_sha256'), name='uniq_doc_hash_empresa')],
            },
        ),
    ]
