# Generated by Django 5.2.5 on 2025-10-27 21:22

import apps.documentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.documentos.models.doc_upload_to)),
                ('nombre_archivo_original', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('es_pdf', models.BooleanField(default=False)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('texto_plano', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('tipo_documento', models.CharField(choices=[('factura_afecta', 'Factura Afecta'), ('factura_exenta', 'Factura Exenta'), ('boleta_afecta', 'Boleta Afecta'), ('boleta_exenta', 'Boleta Exenta'), ('nota_credito', 'Nota de Crédito'), ('desconocido', 'Desconocido')], default='desconocido', max_length=50)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('razon_social_proveedor', models.CharField(blank=True, max_length=255)),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_exento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iva_tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validado_sii', models.BooleanField(default=False)),
                ('sii_track_id', models.CharField(blank=True, max_length=64)),
                ('sii_estado', models.CharField(blank=True, max_length=50)),
                ('sii_glosa', models.CharField(blank=True, max_length=255)),
                ('sii_validado_en', models.DateTimeField(blank=True, null=True)),
                ('ocr_fuente', models.CharField(blank=True, max_length=20)),
                ('ocr_lang', models.CharField(blank=True, max_length=30)),
                ('ocr_engine', models.CharField(blank=True, max_length=50)),
                ('ocr_version', models.CharField(blank=True, max_length=20)),
                ('ocr_json', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['empresa', 'rut_proveedor', 'folio'], name='documentos__empresa_8f85d2_idx'), models.Index(fields=['empresa', 'fecha_emision'], name='documentos__empresa_3faecb_idx'), models.Index(fields=['empresa', 'tipo_documento'], name='documentos__empresa_84c3cc_idx'), models.Index(fields=['estado'], name='documentos__estado_c5e9bd_idx'), models.Index(fields=['creado_en'], name='documentos__creado__e752ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'hash_sha256'), name='uniq_doc_hash_empresa'), models.UniqueConstraint(condition=models.Q(('folio__gt', '')), fields=('empresa', 'rut_proveedor', 'tipo_documento', 'folio'), name='uniq_doc_folio_empresa_proveedor_tipo')],
            },
        ),
    ]
