# Generated by Django 5.2.5 on 2025-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='origen',
            field=models.CharField(db_index=True, default='web', max_length=20),
        ),
    ]
