# Generated by Django 5.2.5 on 2025-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='neto',
            new_name='monto_exento',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='proveedor',
            new_name='razon_social_proveedor',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('factura_afecta', 'Factura Afecta'), ('factura_exenta', 'Factura Exenta'), ('boleta_afecta', 'Boleta Afecta'), ('boleta_exenta', 'Boleta Exenta'), ('nota_credito', 'Nota de Crédito'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='hash_sha256',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='documento',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tamano_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
