# Generated by Django 5.2.5 on 2025-09-02 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_rename_neto_documento_monto_exento_and_more'),
        ('empresas', '0003_alter_empresa_codigo_actividad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='estado_sii',
            new_name='ocr_engine',
        ),
        migrations.AddField(
            model_name='documento',
            name='es_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='iva_tasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre_archivo_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='ocr_fuente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='ocr_lang',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='documento',
            name='ocr_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='sii_estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documento',
            name='sii_glosa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='sii_track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documento',
            name='sii_validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='validado_sii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='documentos__empresa_3faecb_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'tipo_documento'], name='documentos__empresa_84c3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['creado_en'], name='documentos__creado__e752ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('folio__gt', '')), fields=('empresa', 'rut_proveedor', 'tipo_documento', 'folio'), name='uniq_doc_folio_empresa_proveedor_tipo'),
        ),
    ]
