# Generated by Django 5.2.5 on 2025-09-03 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_rename_estado_sii_documento_ocr_engine_and_more'),
        ('empresas', '0003_alter_empresa_codigo_actividad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='documentos__estado_c5e9bd_idx'),
        ),
    ]
