# Generated by Django 5.2.5 on 2025-09-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_documentos__estado_c5e9bd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='texto_plano',
            field=models.TextField(blank=True, default=''),
        ),
    ]
