# Generated by Django 5.2.5 on 2025-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documento_texto_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('factura_afecta', 'Factura Afecta'), ('factura_exenta', 'Factura Exenta'), ('boleta_afecta', 'Boleta Afecta'), ('boleta_exenta', 'Boleta Exenta'), ('nota_credito', 'Nota de Crédito'), ('desconocido', 'Desconocido')], default='desconocido', max_length=50),
        ),
    ]
