# Generated by Django 5.2.5 on 2025-10-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIIContribuyenteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=16, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('actividad_principal', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=32)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIITransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('contribuyente', 'Consulta contribuyente'), ('validar_dte', 'Validar DTE'), ('estado_dte', 'Estado DTE'), ('recibir_dte', 'Recibir DTE')], max_length=32)),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sii_transacciones', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='sii_siitran_endpoin_99de53_idx'), models.Index(fields=['track_id'], name='sii_siitran_track_i_99234d_idx'), models.Index(fields=['estado'], name='sii_siitran_estado_8dd6a4_idx')],
            },
        ),
    ]
